version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stripe_example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  microwitter:
    container_name: Microwitter
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3003:3003
    depends_on:
      - postgres
